[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core>=1",
]

[tool.poetry]
name = "soundfinder"
version = "0.1.0"
description = ""
authors = ["PanMartinez <marcinplotka88@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.1"
sqlmodel = "^0.0.21"
python-dotenv = "^1.0.1"
spotipy = "^2.24.0"

[tool.poetry.dev-dependencies]
pre-commit = "^3.8.0"
pytest = "^8.3.2"
