[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core>=1",
]

[tool.poetry]
name = "soundfinder"
version = "0.1.0"
description = ""
authors = ["PanMartinez <marcinplotka88@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.112.0"
pydantic = "2.8.2"
pydantic_settings = "^2.4.0"
sqlalchemy = "2.0.32"
sqlalchemy-stubs = "^0.4.0"
pyjwt = "^2.9.0"
passlib = "^1.7.4"
python-dotenv = "^1.0.1"
spotipy = "^2.24.0"

[tool.poetry.dev-dependencies]
pre-commit = "^3.8.0"
pytest = "^8.3.2"
