version: "0.0.1"

services:
  spf-core:
    container_name: spf-core
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: 1
    volumes:
      - ./core:/spf-core/core
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db
    command: uvicorn core.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: sounds-pathfinder-test-pass
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_data:
